#include "taskgen.h"
#include "dag_transformer.h"
#include <iostream>
#include <iomanip>
#include "scheduler.h"
#include "np-scheduler.h"

int main() {
    /* THIS PART FOR TASKSETS GENERATED BY UUNIFAST ALGORITHM :: 
    * 
    * 
    int t_n;      // tasks per task set
    int n;        // number of task sets
    double U;     // total utilization

    std::cout << "Enter tasks per task set (t_n): ";
    std::cin >> t_n;

    std::cout << "Enter number of task sets (n): ";
    std::cin >> n;

    std::cout << "Enter total utilization (U): ";
    std::cin >> U;

    TaskGenerator generator;

    auto taskSets = generator.generateTaskSets(n, t_n, U);

    // Print and save the tasksets
    generator.printTaskSets(taskSets);
    generator.saveTaskSetsToFile(taskSets, "generated_tasksets.txt");
    *
    * *
    * * */


    //Hardcoding the taskset for TESTING PURPOSES ONLY:
    std::vector<TaskSet> taskSets;
    TaskSet testSet = {
        // Task 1: S=5, C=2, T=10, D=10, q_td=0.5, q_su=0.5, beta=0, cnt=0
        {2.0, 10.0, 5.0, 5, 0.5, 0.5, 0.0, 0},
        // Task 2: S=5, C=2, T=15, D=15, q_td=0.5, q_su=0.5, beta=0, cnt=0
        {2.0, 15.0, 15.0, 5, 0.5, 0.5, 0.0, 0},
        // Task 3: S=1, C=7, T=12, D=12, q_td=0.0, q_su=0.0, beta=0, cnt=0
        {7.0, 12.0, 12.0, 1, 0.0, 0.0, 0.0, 0}
    };
    taskSets.push_back(testSet);

    // Loop thru each taskset
    for (size_t i = 0; i < taskSets.size(); ++i) {
        std::cout << "Processing Task Set " << i + 1 << ":\n";
        DAGTransformer transformer(taskSets[i]);
        transformer.buildLattice();   // First, build the security lattice
        transformer.buildRelations(); // Then, build the lookup table based on the lattice
        transformer.transformAndPrintBySecurityLevel();

        //get the security relations lable from the dag_transformer class
        const SecurityRelations& securityRelations = transformer.getSecurityRelations();

        // Create a scheduler for each task set:
        Scheduler scheduler(taskSets[i], securityRelations);
        
        // Initialize blocking parameters
        scheduler.initializeBlockingParameters();
        scheduler.printBlockingParameters();


        bool result = scheduler.isSchedulable();
        if (!result)
            std::cout << "Task Set " << i + 1 << " NOT schedulable\n";
        else
            std::cout << "Task Set " << i + 1 << " schedulable\n";

        std::cout<<"After running the scheduler: \n";
        scheduler.printBlockingParameters();
        std::cout << std::endl;
    

        // --- Limited Preemption Scheduler (np-scheduler) ---
        NPScheduler npScheduler(taskSets[i], securityRelations);

        npScheduler.initializeBlockingParameters();
        std::cout << "\n[Limited Preemption Scheduler] Initial blocking parameters:\n";
        npScheduler.printBlockingParameters();

        bool npSched = npScheduler.isSchedulable();
        std::cout << "[Limited Preemption Scheduler] Task set is "
                  << (npSched ? "schedulable" : "NOT schedulable") << "\n";

    }

    return 0;
}